#!/usr/bin/env bash
# Script to install and configure Nginx web server

# Update package index and install Nginx silently
sudo apt-get update -y
sudo apt-get install nginx -y

#Modify Nginx default configuration to make it listen on port 80 on GET request
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

echo "Hello World!" > /var/www/html/index.html

# Restart Nginx without using systemctl
sudo service nginx restart
