#!/usr/bin/env bash
# Script to configure Nginx redirection

# Update package index and install Nginx silently
sudo apt-get update -y
sudo apt-get install nginx -y

# Modify Nginx default configuration to redirect /redirect_me to another page
echo 'server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}' > /etc/nginx/sites-available/default

# Restart Nginx without using systemctl
sudo service nginx restart
