#!/usr/bin/env bash
# Script to configure Nginx custom 404 page

# Update package index and install Nginx silently
sudo apt-get update -y
sudo apt-get install nginx -y

# Modify Ngnix default configuration to use the custom 404 page
echo "server {
	listen 80;
	server_name _;

	error_page 404 /custom_404.html;
	location = /custom_404.html {
		root /var/www/html;
		internal;
	}

	location / {
		try_files \$uri \$uri/ =404
	}
}" > /etc/nginx/sites-available/default

# Restart Nginx without using systemctl
sudo service nginx restart
