#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP response header

sudo apt-get update
sudo apt-get install -y nginx

HOSTNAME=$(hostname)

sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	server_name _;

	add_header X-Served-By "$HOSTNAME";

	location / {
		proxy_pass http://localhost:5000;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}
EOF'

sudo systemctl restart nginx
