#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP response header

sudo apt-get update
sudo apt-get install -y nginx

sudo service nginx start
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo systemctl restart nginx
