#!/usr/bin/env bash

set -e

MYSQL_PASSWORD="projectcorrection280hbtn"

mysql -uroot -p$MYSQL_PASSWORD -e "CREATE USER 'replica_user'@'%' IDENTIFIED BY 'gabriel';"
mysql -uroot -p$MYSQL_PASSWORD -e "GRANT REPLICATION SLAVE ON *.* TO 'replica_user'@'%';"
mysql -uroot -p$MYSQL_PASSWORD -e "GRANT SELECT ON mysql.user TO 'holberton_user'@'localhost';"
mysql -uroot -p$MYSQL_PASSWORD -e "FLUSH PRIVILEGES;"
