#!/usr/bin/env bash
# This script displays the PID and process name of processes containing
# the word 'bash'

for pid in /proc/*; do
   if [[ -d "$pid" && $(cat "$pid/comm") == *bash* ]]; then
	   echo "$(basename $pid): $(cat "$pid/comm")"
   fi
done
