#!/usr/bin/env bash
# This script displays the PID and process name of processes containing
# the word 'bash'

for pid in /proc/[0-9]*; do
   if [[ $(cat "/proc/$pid/comm") == *bash* ]]; then
      echo "$pid: $(cat "/proc/$pid/comm")"
   fi
done
