#!/usr/bin/env bash
# This script displays "To infinity and beyond" with a pause of  seconds between each iteration
# It also displays "I am invicible!!!" when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
   echo "To infinity and beyond"
   sleep 2
done
