#!/usr/bin/env bash
# This script prints "Best School" 10 times and prints with "Hi" on the ninth

counter=1
while [ $counter -le 10 ]
do
   echo "Best School"
   if [ $counter -eq 9 ]
   then
      echo "Hi"
   fi
   counter=$((counter+1))
done
