#!/usr/bin/env bash
# This script prints "Bad luck" for the 4 iteration, "Good luck" for the
# 8th iteration and "Best School" for the other iterations

counter=1
while [ $counter -le 10 ]
do
   if [ $counter -eq 4 ]
   then
      echo "Bad luck"
   elif [ $counter -eq 8 ]
   then
      echo "Good luck"
   else
      echo "Best School"
   fi
   counter=$((counter+1))
done
