#!/usr/bin/env bash
# This script prints numbers from 1 to 20 and special message for the 
# 4th, 9th and 17th iterations

counter=1
while [ $counter -le 20 ]
do
   echo $counter
   case $counter in
	   "4") echo "bad luck from China"
		   ;;
	   "9") echo "bad luck from Japan"
		   ;;
	   "17") echo "bad luck from Italy"
		   ;;
   esac
   counter=$((counter+1))
done
