#!/usr/bin/env bash
# This script configures DNS settings for localhost and facebook

cp /etc/hosts /etc/hosts.bak

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

cat /etc/hosts
