#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default

systemctl restart nginx
