#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080
{
	echo "events {"
	echo "    worker_connections 1024;"
	echo "}"
} > /etc/nginx/nginx.conf

service nginx restart
