#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080
sudo apt-get install -y nginx
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
usermod -aG www-data nginx
chown -R nginx:nginx /var/lib/nginx /var/log/nginx /run/nginx.pid /var/www/html
sudo service nginx start
